In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:/PPBI PROJECT/Data/Raw/Specific_purpose_of_kidnapping_and_aduction.csv")

In [3]:
df.columns

Index(['Area_Name', 'Year', 'Group_Name', 'Sub_Group_Name',
       'K_A_Cases_Reported', 'K_A_Female_10_15_Years',
       'K_A_Female_15_18_Years', 'K_A_Female_18_30_Years',
       'K_A_Female_30_50_Years', 'K_A_Female_Above_50_Years',
       'K_A_Female_Total', 'K_A_Female_Upto_10_Years', 'K_A_Grand_Total',
       'K_A_Male_10_15_Years', 'K_A_Male_15_18_Years', 'K_A_Male_18_30_Years',
       'K_A_Male_30_50_Years', 'K_A_Male_Above_50_Years', 'K_A_Male_Total',
       'K_A_Male_Upto_10_Years'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3569 entries, 0 to 3568
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Area_Name                  3569 non-null   str
 1   Year                       3569 non-null   int64
 2   Group_Name                 3569 non-null   str
 3   Sub_Group_Name             3569 non-null   str
 4   K_A_Cases_Reported         3562 non-null   float64
 5   K_A_Female_10_15_Years     3178 non-null   float64
 6   K_A_Female_15_18_Years     3231 non-null   float64
 7   K_A_Female_18_30_Years     3260 non-null   float64
 8   K_A_Female_30_50_Years     3119 non-null   float64
 9   K_A_Female_Above_50_Years  2948 non-null   float64
 10  K_A_Female_Total           3407 non-null   float64
 11  K_A_Female_Upto_10_Years   3074 non-null   float64
 12  K_A_Grand_Total            3510 non-null   float64
 13  K_A_Male_10_15_Years       3086 non-null   float64
 14  K_A_Male_15_18_Years       3081 non-null   float64
 15  K_A_Male_18_30_Years       3202 non-null   float64
 16  K_A_Male_30_50_Years       3152 non-null   float64
 17  K_A_Male_Above_50_Years    3011 non-null   float64
 18  K_A_Male_Total             3312 non-null   float64
 19  K_A_Male_Upto_10_Years     3098 non-null   float64
dtypes: float64(16), int64(1), str(3)
memory usage: 557.8 KB

In [5]:
df.drop(columns = [
    "K_A_Female_Upto_10_Years",
    "K_A_Female_10_15_Years",
    "K_A_Female_15_18_Years",
    "K_A_Female_18_30_Years",
    "K_A_Female_30_50_Years",
    "K_A_Female_Above_50_Years",
    "K_A_Male_Upto_10_Years",
    "K_A_Male_10_15_Years",
    "K_A_Male_15_18_Years",
    "K_A_Male_18_30_Years",
    "K_A_Male_30_50_Years",
    "K_A_Male_Above_50_Years"
], inplace=True)

In [6]:
df.rename(columns={
    "Area_Name": "State",
    "Sub_Group_Name": "Subgroup_Name",
    "K_A_Cases_Reported": "Cases_Reported",
    "K_A_Female_Total": "Female_Total",
    "K_A_Male_Total": "Male_Total",
    "K_A_Grand_Total": "Total_Cases"
}, inplace=True)

In [7]:
df.isnull().sum()

State               0
Year                0
Group_Name          0
Subgroup_Name       0
Cases_Reported      7
Female_Total      162
Total_Cases        59
Male_Total        257
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
cols = ['Cases_Reported', 'Female_Total', 'Male_Total', 'Total_Cases']

df[cols] = df[cols].fillna(0)

In [11]:
df[cols] = df[cols].astype(int)

In [12]:
df['Female_Percentage'] = (
    df['Female_Total'] / df['Total_Cases']
) * 100

In [13]:
df['Male_Percentage'] = (
    df['Male_Total'] / df ['Total_Cases']
) * 100

In [14]:
df.head()

,State,Year,Group_Name,Subgroup_Name,Cases_Reported,Female_Total,Total_Cases,Male_Total,Female_Percentage,Male_Percentage
0,Andhra Pradesh,2001,Kidnap - For Adoption,01. For Adoption,8,5,8,3,62.5,37.5
1,Arunachal Pradesh,2001,Kidnap - For Adoption,01. For Adoption,0,0,0,0,NaN,NaN
2,Assam,2001,Kidnap - For Adoption,01. For Adoption,0,0,0,0,NaN,NaN
3,Bihar,2001,Kidnap - For Adoption,01. For Adoption,18,0,18,18,0.0,100.0
4,Chandigarh,2001,Kidnap - For Adoption,01. For Adoption,0,0,0,0,NaN,NaN

In [15]:
df.isnull().sum()

State                   0
Year                    0
Group_Name              0
Subgroup_Name           0
Cases_Reported          0
Female_Total            0
Total_Cases             0
Male_Total              0
Female_Percentage    1177
Male_Percentage      1177
dtype: int64

In [16]:
df['Gender_Gap'] = (df['Female_Total'] - df['Male_Total'])

In [17]:
yearly_cases = df.groupby('Year')['Cases_Reported'].sum()

growth = yearly_cases.pct_change() * 100

print(growth)

Year
2001          NaN
2002     4.277946
2003   -14.258894
2004    20.103803
2005    -0.378123
2006     4.658624
2007     6.743805
2008    19.636790
2009    10.509145
2010     4.053537
Name: Cases_Reported, dtype: float64

In [18]:
df.drop(columns=[
    'Female_Percentage',
    'Male_Percentage'
], inplace=True)

In [19]:
df.describe()

,Year,Cases_Reported,Female_Total,Total_Cases,Male_Total,Gender_Gap
count,3202.000000,3202.000000,3202.000000,3202.000000,3202.000000,3202.000000
mean,2005.505309,155.694878,110.808245,157.683635,46.875390,63.932854
std,2.839033,458.781691,352.396807,463.191666,160.365187,291.983709
min,2001.000000,0.000000,0.000000,0.000000,0.000000,-1556.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
50%,2005.000000,4.000000,1.000000,5.000000,0.000000,0.000000
75%,2008.000000,59.000000,30.000000,62.000000,15.000000,7.000000
max,2010.000000,6321.000000,5468.000000,6323.000000,2465.000000,4613.000000

In [20]:
df.isna().sum()

State             0
Year              0
Group_Name        0
Subgroup_Name     0
Cases_Reported    0
Female_Total      0
Total_Cases       0
Male_Total        0
Gender_Gap        0
dtype: int64

In [21]:
df.to_csv("kidnapping_data.csv", index=False)