In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:/PPBI PROJECT/Data/Raw/Arrest_under_crime_against_women.csv")

In [3]:
df.columns

Index(['Area_Name', 'Year', 'Group_Name', 'Sub_Group_Name',
       'Persons_Acquitted',
       'Persons_against_whom_cases_Compounded_or_Withdrawn',
       'Persons_Arrested', 'Persons_Chargesheeted', 'Persons_Convicted',
       'Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_beginning',
       'Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_end',
       'Persons_in_Custody_or_on_Bail_during_Trial_at_Year_End',
       'Persons_Released_or_Freed_by_Police_or_Magistrate_before_Trial_for_want_of_evidence_or_any_other_reason',
       'Persons_Trial_Completed', 'Persons_under_Trial_at_Year_beginning',
       'Total_Persons_under_Trial', 'Unnamed: 16'],
      dtype='str')

In [4]:
df.drop(columns=[
    "Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_beginning",
    "Persons_in_Custody_or_on_Bail_during_Investigation_at_Year_end",
    "Persons_in_Custody_or_on_Bail_during_Trial_at_Year_End"
], inplace=True)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4165 entries, 0 to 4164
Data columns (total 14 columns):
 #   Column                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                   --------------  -----
 0   Area_Name                                                                                                4165 non-null   str
 1   Year                                                                                                     4165 non-null   int64
 2   Group_Name                                                                                               4165 non-null   str
 3   Sub_Group_Name                                                                                           4165 non-null   str
 4   Persons_Acquitted                                                                                        4165 non-null   int64
 5   Persons_against_whom_cases_Compounded_or_Withdrawn                                                       4165 non-null   int64
 6   Persons_Arrested                                                                                         4165 non-null   int64
 7   Persons_Chargesheeted                                                                                    4165 non-null   int64
 8   Persons_Convicted                                                                                        4165 non-null   int64
 9   Persons_Released_or_Freed_by_Police_or_Magistrate_before_Trial_for_want_of_evidence_or_any_other_reason  4165 non-null   int64
 10  Persons_Trial_Completed                                                                                  4165 non-null   int64
 11  Persons_under_Trial_at_Year_beginning                                                                    4165 non-null   int64
 12  Total_Persons_under_Trial                                                                                4165 non-null   int64
 13  Unnamed: 16                                                                                              1400 non-null   float64
dtypes: float64(1), int64(10), str(3)
memory usage: 455.7 KB

In [6]:
rename_map = {
    "Area_Name": "area",
    "Year": "year",
    "Group_Name": "crime_group",
    "Sub_Group_Name": "crime_subgroup",

    "Persons_Acquitted": "acquitted",
    "Persons_against_whom_cases_Compounded_or_Withdrawn": "withdrawn",
    "Persons_Arrested": "arrested",
    "Persons_Chargesheeted": "chargesheeted",
    "Persons_Convicted": "convicted",
    "Persons_Released_or_Freed_by_Police_or_Magistrate_before_Trial_for_want_of_evidence_or_any_other_reason": "released_before_trial",
    "Persons_Trial_Completed": "trial_completed"
}

In [7]:
df.rename(columns=rename_map,inplace = True)

In [8]:
df.columns.str.strip()

Index(['area', 'year', 'crime_group', 'crime_subgroup', 'acquitted',
       'withdrawn', 'arrested', 'chargesheeted', 'convicted',
       'released_before_trial', 'trial_completed',
       'Persons_under_Trial_at_Year_beginning', 'Total_Persons_under_Trial',
       'Unnamed: 16'],
      dtype='str')

In [9]:
df.drop(columns=['Unnamed: 16'], inplace=True)

In [10]:
df.rename(columns={
    'crime_group': 'Group_Name',
    'crime_subgroup': 'Sub_Group',
    'area' :'state'
}, inplace=True)

In [11]:
df.columns = df.columns.str.title()

In [12]:
df.isnull().sum()

State                                    0
Year                                     0
Group_Name                               0
Sub_Group                                0
Acquitted                                0
Withdrawn                                0
Arrested                                 0
Chargesheeted                            0
Convicted                                0
Released_Before_Trial                    0
Trial_Completed                          0
Persons_Under_Trial_At_Year_Beginning    0
Total_Persons_Under_Trial                0
dtype: int64

In [13]:
df.describe()

,Year,Acquitted,Withdrawn,Arrested,Chargesheeted,Convicted,Released_Before_Trial,Trial_Completed,Persons_Under_Trial_At_Year_Beginning,Total_Persons_Under_Trial
count,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000,4165.000000
mean,2005.478992,1257.048499,126.871309,1245.567107,1209.839376,274.527491,201.059064,823.381273,4259.468187,5510.963505
std,2.875474,2015.782332,534.446808,4240.291826,3942.156448,1120.302654,914.604023,2812.408364,16513.711755,20133.916649
min,2001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2003.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2005.000000,662.000000,0.000000,6.000000,22.000000,5.000000,1.000000,4.000000,47.000000,90.000000
75%,2008.000000,1961.000000,17.000000,503.000000,602.000000,121.000000,32.000000,352.000000,1345.000000,2156.000000
max,2010.000000,24476.000000,8541.000000,63332.000000,47745.000000,27706.000000,16058.000000,48532.000000,266808.000000,306044.000000

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.groupby('Year')['Convicted'].sum()
#year wise trend

Year
2001    108357
2002    123514
2003    104805
2004    111971
2005    116428
2006    119051
2007    119139
2008     73977
2009    127341
2010    138824
Name: Convicted, dtype: int64

In [16]:
df.groupby('State')['Arrested'].sum()
#Area wise crime analysis

State
Andaman & Nicobar Islands      1189
Andhra Pradesh               558289
Arunachal Pradesh              3378
Assam                        164471
Bihar                        224737
Chandigarh                     4319
Chhattisgarh                 108159
Dadra & Nagar Haveli            511
Daman & Diu                     417
Delhi                         79883
Goa                            2960
Gujarat                      326298
Haryana                      126698
Himachal Pradesh              24704
Jammu & Kashmir               65569
Jharkhand                     71647
Karnataka                    183606
Kerala                       192786
Lakshadweep                      27
Madhya Pradesh               481531
Maharashtra                  641671
Manipur                        2571
Meghalaya                      2355
Mizoram                        2708
Nagaland                        837
Odisha                       173133
Puducherry                     3637
Punjab                        76892
Rajasthan                    264578
Sikkim                          907
Tamil Nadu                   186861
Tripura                       24870
Uttar Pradesh                788753
Uttarakhand                   37518
West Bengal                  359317
Name: Arrested, dtype: int64

In [17]:
#crime group analysis
df.groupby('Group_Name')['Convicted'].sum()

Group_Name
Cruelty by Husband and Relatives                      173263
Dowry Deaths                                           54518
Dowry Prohibition Act                                  77518
Immoral Traffic (Prevention) Act                      101530
Importation of Girls                                     119
Indecent Representation of Women (Prohibition) Act     14790
Kidnapping & Abduction - Women & Girls                 42335
Molestation                                            86653
Rape                                                   50812
Sati Prevention Act                                       25
Sexual harassment                                      57676
Total Crime Against Women                             484168
Name: Convicted, dtype: int64

In [18]:
df['High_Crime_Area'] = df['Arrested'] > df['Arrested'].median()

In [19]:
df.to_csv("cleaned_Arrest.csv", index=False)

In [20]:
df

,State,Year,Group_Name,Sub_Group,Acquitted,Withdrawn,Arrested,Chargesheeted,Convicted,Released_Before_Trial,Trial_Completed,Persons_Under_Trial_At_Year_Beginning,Total_Persons_Under_Trial,High_Crime_Area
0,Andaman & Nicobar Islands,2001,Rape,01. Rape,6,0,3,3,0,0,6,48,51,False
1,Andhra Pradesh,2001,Rape,01. Rape,1168,13,1150,1021,246,34,1414,2597,3618,True
2,Arunachal Pradesh,2001,Rape,01. Rape,1,0,51,31,2,15,3,319,350,True
3,Assam,2001,Rape,01. Rape,403,14,928,585,120,190,523,2283,2868,True
4,Bihar,2001,Rape,01. Rape,756,0,1400,1302,217,241,973,5634,6936,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4160,Tamil Nadu,2010,Total Crime Against Women,12. Total Crimes Against Women,5583,4,9649,8841,2809,177,8392,20814,29655,True
4161,Tripura,2010,Total Crime Against Women,12. Total Crimes Against Women,1323,154,2127,1611,144,340,1467,2193,3804,True
4162,Uttar Pradesh,2010,Total Crime Against Women,12. Total Crimes Against Women,20826,1469,58330,41235,27706,16058,48532,125133,166368,True
4163,Uttarakhand,2010,Total Crime Against Women,12. Total Crimes Against Women,1052,78,1750,1683,1075,77,2127,6286,7969,True
4164,West Bengal,2010,Total Crime Against Women,12. Total Crimes Against Women,11372,670,26549,28005,628,1250,12000,109399,137404,True